-- Create the products table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  price text not null, -- using text to allow currency symbols like '$120.00' easily for now
  tag text,
  image_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create a storage bucket for product images
insert into storage.buckets (id, name, public) 
values ('product-images', 'product-images', true);

-- Set up Row Level Security (RLS)
-- Enable RLS
alter table products enable row level security;

-- Allow read access to everyone
create policy "Public Products are viewable by everyone"
  on products
  for select
  using (true);

-- Allow insert access to everyone (FOR DEMO/ADMIN PURPOSE - in production this should be authenticated)
create policy "Enable insert for everyone"
  on products
  for insert
  with check (true);

-- Storage policies
create policy "Give public access to product-images"
  on storage.objects
  for select
  using ( bucket_id = 'product-images' );

create policy "Enable upload for everyone"
  on storage.objects
  for insert
  with check ( bucket_id = 'product-images' );
